# Generated by Django 4.0.4 on 2022-05-20 16:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('enseignant', 'enseignant'), ('doctorant', 'doctorant')], max_length=190, null=True)),
                ('nbplace', models.IntegerField(null=True)),
                ('nbdispo', models.IntegerField(null=True)),
                ('nbocc', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=190, null=True)),
                ('prenom', models.CharField(max_length=190, null=True)),
                ('role', models.CharField(choices=[('enseignant', 'enseignant'), ('doctorant', 'doctorant')], max_length=190, null=True)),
                ('telephone', models.CharField(max_length=190, null=True)),
                ('mdp', models.CharField(max_length=190, null=True)),
                ('date_created', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
