# Generated by Django 4.0.4 on 2022-05-20 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_notification_reservation_date_enter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='reservationID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.reservation'),
        ),
        migrations.AddField(
            model_name='notification',
            name='utilisateurID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.utilisateur'),
        ),
        migrations.AddField(
            model_name='place',
            name='salleID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.salle'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='placeID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.place'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='utilisateurID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.utilisateur'),
        ),
    ]
