# Generated by Django 4.0.4 on 2022-05-23 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_notification_reservationid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='mdp',
        ),
    ]
