# Generated by Django 4.0.4 on 2022-05-29 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_utilisateur_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='etat',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='role',
        ),
        migrations.AlterField(
            model_name='salle',
            name='nom',
            field=models.CharField(choices=[('doctorant', 'doctorant')], max_length=190, null=True),
        ),
    ]
