# Generated by Django 4.0.4 on 2022-05-29 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_remove_reservation_etat_remove_utilisateur_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='avatar',
            field=models.ImageField(blank=True, default='profile.png', upload_to='profile_pictures'),
        ),
    ]
