# Generated by Django 4.0.4 on 2022-05-30 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_alter_utilisateur_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='avatar',
            field=models.ImageField(default='profile.png', upload_to=''),
        ),
    ]
