# Generated by Django 4.0.4 on 2022-05-30 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_rename_nom_utilisateur_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateur',
            old_name='name',
            new_name='nom',
        ),
    ]
