# Generated by Django 4.0.4 on 2022-05-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_rename_name_utilisateur_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
