# Generated by Django 4.0.4 on 2022-05-31 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_alter_utilisateur_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salle',
            name='nbdispo',
        ),
        migrations.RemoveField(
            model_name='salle',
            name='nbocc',
        ),
        migrations.RemoveField(
            model_name='salle',
            name='nbplace',
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='avatar',
            field=models.ImageField(blank=True, default='profile.png', null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
