# Generated by Django 4.0.4 on 2022-06-02 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_reservation_id_alter_reservation_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.place'),
        ),
    ]
